export default [
  {
    chain_level1: "先进装备制造",
    chain_level2: "工程机械",
    chain_level3: "工程机械原材料及零部件",
    chain_level4: "工程机械液压系统及零部件",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "工程机械",
    chain_level3: "工程机械原材料及零部件",
    chain_level4: "工程机械用内燃机",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "工程机械",
    chain_level3: "工程机械原材料及零部件",
    chain_level4: "工程机械用履带",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "工程机械",
    chain_level3: "工程机械原材料及零部件",
    chain_level4: "工程机械用轮胎",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "工程机械",
    chain_level3: "工程机械原材料及零部件",
    chain_level4: "工程机械用轴承",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "工程机械",
    chain_level3: "工程机械原材料及零部件",
    chain_level4: "工程机械用钢材",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "工程机械",
    chain_level3: "工程机械原材料及零部件",
    chain_level4: "工程机械用齿轮和传动部件",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "工程机械",
    chain_level3: "工程机械原材料及零部件",
    chain_level4: null,
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "工程机械",
    chain_level3: "工程机械整机制造",
    chain_level4: "压实机械",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "工程机械",
    chain_level3: "工程机械整机制造",
    chain_level4: "挖掘机械",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "工程机械",
    chain_level3: "工程机械整机制造",
    chain_level4: "桩工机械",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "工程机械",
    chain_level3: "工程机械整机制造",
    chain_level4: "电梯、自动扶梯及升降机",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "工程机械",
    chain_level3: "工程机械整机制造",
    chain_level4: "起重机械",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "工程机械",
    chain_level3: "工程机械整机制造",
    chain_level4: "道路机械",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "工程机械",
    chain_level3: "工程机械整机制造",
    chain_level4: "钢筋混凝土机械",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "工程机械",
    chain_level3: "工程机械整机制造",
    chain_level4: "铲土运输机械",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "工程机械",
    chain_level3: "工程机械整机制造",
    chain_level4: null,
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "工程机械",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "增材设备",
    chain_level4: "3D打印设备",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "增材设备",
    chain_level4: "增材制造设备材料及零部件",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "增材设备",
    chain_level4: null,
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "数控机床",
    chain_level4: "数控机床功能部件及附件制造",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "数控机床",
    chain_level4: "数控金属机床",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "数控机床",
    chain_level4: "机床功能部件及附件制造",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "数控机床",
    chain_level4: null,
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "智能仪器仪表",
    chain_level4: "供应用仪器仪表制造",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "智能仪器仪表",
    chain_level4: "实验分析仪器制造",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "智能仪器仪表",
    chain_level4: null,
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "智能制造装备关键基础零部件及控制系统",
    chain_level4: "减速器",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "智能制造装备关键基础零部件及控制系统",
    chain_level4: "工业自动化控制系统",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "智能制造装备关键基础零部件及控制系统",
    chain_level4: "控制器",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "智能制造装备关键基础零部件及控制系统",
    chain_level4: "智能控制系统",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "智能制造装备关键基础零部件及控制系统",
    chain_level4: null,
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "智能制造装备关键基础零部件及智能系统",
    chain_level4: "伺服电机",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "智能制造装备关键基础零部件及智能系统",
    chain_level4: "伺服编码器",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "智能制造装备关键基础零部件及智能系统",
    chain_level4: "伺服驱动器",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "智能制造装备关键基础零部件及智能系统",
    chain_level4: "减速器",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "智能制造装备关键基础零部件及智能系统",
    chain_level4: "工业自动化控制系统",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "智能制造装备关键基础零部件及智能系统",
    chain_level4: "工业软件系统",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "智能制造装备关键基础零部件及智能系统",
    chain_level4: "控制器",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "智能制造装备关键基础零部件及智能系统",
    chain_level4: "智能传感器",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "智能制造装备关键基础零部件及智能系统",
    chain_level4: "精密轴承",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "智能制造装备关键基础零部件及智能系统",
    chain_level4: null,
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "机器人",
    chain_level4: "工业机器人",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "机器人",
    chain_level4: "服务机器人",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: "机器人",
    chain_level4: null,
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "智能制造装备",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "特种电机",
    chain_level3: "特种电机关键材料",
    chain_level4: "电解铜",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "特种电机",
    chain_level3: "特种电机关键材料",
    chain_level4: "硅钢",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "特种电机",
    chain_level3: "特种电机关键材料",
    chain_level4: "碳结钢",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "特种电机",
    chain_level3: "特种电机关键材料",
    chain_level4: "绝缘材料",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "特种电机",
    chain_level3: "特种电机关键材料",
    chain_level4: null,
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "特种电机",
    chain_level3: "特种电机整机",
    chain_level4: "伺服驱动与控制类电机",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "特种电机",
    chain_level3: "特种电机整机",
    chain_level4: "信号检测类特种电机",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "特种电机",
    chain_level3: "特种电机整机",
    chain_level4: "感应电机",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "特种电机",
    chain_level3: "特种电机整机",
    chain_level4: "永磁电机",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "特种电机",
    chain_level3: "特种电机整机",
    chain_level4: "电动测功机",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "特种电机",
    chain_level3: "特种电机整机",
    chain_level4: "磁阻类特种电机",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "特种电机",
    chain_level3: "特种电机整机",
    chain_level4: null,
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "特种电机",
    chain_level3: "特种电机结构部件",
    chain_level4: "定子总成",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "特种电机",
    chain_level3: "特种电机结构部件",
    chain_level4: "特种电机其他结构部件",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "特种电机",
    chain_level3: "特种电机结构部件",
    chain_level4: "转子总成",
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "特种电机",
    chain_level3: "特种电机结构部件",
    chain_level4: null,
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: "特种电机",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "先进装备制造",
    chain_level2: null,
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "建材家具",
    chain_level2: "家具",
    chain_level3: "下游应用",
    chain_level4: "文体家具",
  },
  {
    chain_level1: "建材家具",
    chain_level2: "家具",
    chain_level3: "下游应用",
    chain_level4: "校用家具",
  },
  {
    chain_level1: "建材家具",
    chain_level2: "家具",
    chain_level3: "下游应用",
    chain_level4: null,
  },
  {
    chain_level1: "建材家具",
    chain_level2: "家具",
    chain_level3: "中游生产",
    chain_level4: "加工制造",
  },
  {
    chain_level1: "建材家具",
    chain_level2: "家具",
    chain_level3: "中游生产",
    chain_level4: null,
  },
  {
    chain_level1: "建材家具",
    chain_level2: "家具",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "建材家具",
    chain_level2: "建筑陶瓷",
    chain_level3: "中游产品",
    chain_level4: "陶瓷砖",
  },
  {
    chain_level1: "建材家具",
    chain_level2: "建筑陶瓷",
    chain_level3: "中游产品",
    chain_level4: null,
  },
  {
    chain_level1: "建材家具",
    chain_level2: "建筑陶瓷",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "建材家具",
    chain_level2: "装配式建筑",
    chain_level3: "上游建筑设计",
    chain_level4: "装配式混凝土建筑(PC)",
  },
  {
    chain_level1: "建材家具",
    chain_level2: "装配式建筑",
    chain_level3: "上游建筑设计",
    chain_level4: null,
  },
  {
    chain_level1: "建材家具",
    chain_level2: "装配式建筑",
    chain_level3: "中游生产施工",
    chain_level4: "安装施工",
  },
  {
    chain_level1: "建材家具",
    chain_level2: "装配式建筑",
    chain_level3: "中游生产施工",
    chain_level4: "预制构件生产",
  },
  {
    chain_level1: "建材家具",
    chain_level2: "装配式建筑",
    chain_level3: "中游生产施工",
    chain_level4: null,
  },
  {
    chain_level1: "建材家具",
    chain_level2: "装配式建筑",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "建材家具",
    chain_level2: null,
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "数字经济",
    chain_level2: "产业数字化",
    chain_level3: "农业数字化",
    chain_level4: "智慧农业",
  },
  {
    chain_level1: "数字经济",
    chain_level2: "产业数字化",
    chain_level3: "农业数字化",
    chain_level4: null,
  },
  {
    chain_level1: "数字经济",
    chain_level2: "产业数字化",
    chain_level3: "工业数字化",
    chain_level4: "数字化建筑业",
  },
  {
    chain_level1: "数字经济",
    chain_level2: "产业数字化",
    chain_level3: "工业数字化",
    chain_level4: "智能制造",
  },
  {
    chain_level1: "数字经济",
    chain_level2: "产业数字化",
    chain_level3: "工业数字化",
    chain_level4: null,
  },
  {
    chain_level1: "数字经济",
    chain_level2: "产业数字化",
    chain_level3: "政务民生产业数字化",
    chain_level4: "数字社会",
  },
  {
    chain_level1: "数字经济",
    chain_level2: "产业数字化",
    chain_level3: "政务民生产业数字化",
    chain_level4: "智能交通",
  },
  {
    chain_level1: "数字经济",
    chain_level2: "产业数字化",
    chain_level3: "政务民生产业数字化",
    chain_level4: null,
  },
  {
    chain_level1: "数字经济",
    chain_level2: "产业数字化",
    chain_level3: "服务业数字化",
    chain_level4: "数字金融",
  },
  {
    chain_level1: "数字经济",
    chain_level2: "产业数字化",
    chain_level3: "服务业数字化",
    chain_level4: "智慧物流",
  },
  {
    chain_level1: "数字经济",
    chain_level2: "产业数字化",
    chain_level3: "服务业数字化",
    chain_level4: "智能交通",
  },
  {
    chain_level1: "数字经济",
    chain_level2: "产业数字化",
    chain_level3: "服务业数字化",
    chain_level4: null,
  },
  {
    chain_level1: "数字经济",
    chain_level2: "产业数字化",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "数字经济",
    chain_level2: "数字产业化",
    chain_level3: "数字产品制造业",
    chain_level4: "智能设备制造",
  },
  {
    chain_level1: "数字经济",
    chain_level2: "数字产业化",
    chain_level3: "数字产品制造业",
    chain_level4: "电子核心制造",
  },
  {
    chain_level1: "数字经济",
    chain_level2: "数字产业化",
    chain_level3: "数字产品制造业",
    chain_level4: "网络与通信终端制造",
  },
  {
    chain_level1: "数字经济",
    chain_level2: "数字产业化",
    chain_level3: "数字产品制造业",
    chain_level4: null,
  },
  {
    chain_level1: "数字经济",
    chain_level2: "数字产业化",
    chain_level3: "数字产品服务业",
    chain_level4: "数字产品维修",
  },
  {
    chain_level1: "数字经济",
    chain_level2: "数字产业化",
    chain_level3: "数字产品服务业",
    chain_level4: "数字产品零售",
  },
  {
    chain_level1: "数字经济",
    chain_level2: "数字产业化",
    chain_level3: "数字产品服务业",
    chain_level4: null,
  },
  {
    chain_level1: "数字经济",
    chain_level2: "数字产业化",
    chain_level3: "数字技术应用业",
    chain_level4: "互联网、大数据与云计算",
  },
  {
    chain_level1: "数字经济",
    chain_level2: "数字产业化",
    chain_level3: "数字技术应用业",
    chain_level4: "软件及信息服务",
  },
  {
    chain_level1: "数字经济",
    chain_level2: "数字产业化",
    chain_level3: "数字技术应用业",
    chain_level4: null,
  },
  {
    chain_level1: "数字经济",
    chain_level2: "数字产业化",
    chain_level3: "数字要素驱动业",
    chain_level4: "互联网驱动业",
  },
  {
    chain_level1: "数字经济",
    chain_level2: "数字产业化",
    chain_level3: "数字要素驱动业",
    chain_level4: "其他数字要素驱动业",
  },
  {
    chain_level1: "数字经济",
    chain_level2: "数字产业化",
    chain_level3: "数字要素驱动业",
    chain_level4: null,
  },
  {
    chain_level1: "数字经济",
    chain_level2: "数字产业化",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "数字经济",
    chain_level2: null,
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: "文旅产业资源与规划建设",
    chain_level3: "文旅产业资源",
    chain_level4: "文旅住宿",
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: "文旅产业资源与规划建设",
    chain_level3: "文旅产业资源",
    chain_level4: "文旅购物",
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: "文旅产业资源与规划建设",
    chain_level3: "文旅产业资源",
    chain_level4: "文旅餐饮",
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: "文旅产业资源与规划建设",
    chain_level3: "文旅产业资源",
    chain_level4: null,
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: "文旅产业资源与规划建设",
    chain_level3: "文旅项目规划与建设",
    chain_level4: "文旅项目建设",
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: "文旅产业资源与规划建设",
    chain_level3: "文旅项目规划与建设",
    chain_level4: "文旅项目规划设计",
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: "文旅产业资源与规划建设",
    chain_level3: "文旅项目规划与建设",
    chain_level4: null,
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: "文旅产业资源与规划建设",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: "文旅产品与投资运营",
    chain_level3: "文旅业态",
    chain_level4: "休闲度假",
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: "文旅产品与投资运营",
    chain_level3: "文旅业态",
    chain_level4: "康养旅游",
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: "文旅产品与投资运营",
    chain_level3: "文旅业态",
    chain_level4: "生态和谐游",
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: "文旅产品与投资运营",
    chain_level3: "文旅业态",
    chain_level4: "研学基地",
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: "文旅产品与投资运营",
    chain_level3: "文旅业态",
    chain_level4: null,
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: "文旅产品与投资运营",
    chain_level3: "文旅项目投资运营",
    chain_level4: "文旅项目投资",
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: "文旅产品与投资运营",
    chain_level3: "文旅项目投资运营",
    chain_level4: "文旅项目运营与管理",
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: "文旅产品与投资运营",
    chain_level3: "文旅项目投资运营",
    chain_level4: null,
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: "文旅产品与投资运营",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: "文旅产品广告与营销服务",
    chain_level3: "其他文旅服务",
    chain_level4: null,
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: "文旅产品广告与营销服务",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "文旅商贸",
    chain_level2: null,
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "新能源锂电",
    chain_level2: "锂电池核心原材料与生产设备",
    chain_level3: "锂电池核心原材料",
    chain_level4: "正极材料",
  },
  {
    chain_level1: "新能源锂电",
    chain_level2: "锂电池核心原材料与生产设备",
    chain_level3: "锂电池核心原材料",
    chain_level4: "电解液",
  },
  {
    chain_level1: "新能源锂电",
    chain_level2: "锂电池核心原材料与生产设备",
    chain_level3: "锂电池核心原材料",
    chain_level4: "负极材料",
  },
  {
    chain_level1: "新能源锂电",
    chain_level2: "锂电池核心原材料与生产设备",
    chain_level3: "锂电池核心原材料",
    chain_level4: "锂电池辅材",
  },
  {
    chain_level1: "新能源锂电",
    chain_level2: "锂电池核心原材料与生产设备",
    chain_level3: "锂电池核心原材料",
    chain_level4: "隔膜",
  },
  {
    chain_level1: "新能源锂电",
    chain_level2: "锂电池核心原材料与生产设备",
    chain_level3: "锂电池核心原材料",
    chain_level4: null,
  },
  {
    chain_level1: "新能源锂电",
    chain_level2: "锂电池核心原材料与生产设备",
    chain_level3: "锂电生产设备",
    chain_level4: "电芯中段设备",
  },
  {
    chain_level1: "新能源锂电",
    chain_level2: "锂电池核心原材料与生产设备",
    chain_level3: "锂电生产设备",
    chain_level4: "电芯前段设备",
  },
  {
    chain_level1: "新能源锂电",
    chain_level2: "锂电池核心原材料与生产设备",
    chain_level3: "锂电生产设备",
    chain_level4: "电芯后段设备",
  },
  {
    chain_level1: "新能源锂电",
    chain_level2: "锂电池核心原材料与生产设备",
    chain_level3: "锂电生产设备",
    chain_level4: null,
  },
  {
    chain_level1: "新能源锂电",
    chain_level2: "锂电池核心原材料与生产设备",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "新能源锂电",
    chain_level2: "锂电池生产制造",
    chain_level3: "储能锂电池",
    chain_level4: null,
  },
  {
    chain_level1: "新能源锂电",
    chain_level2: "锂电池生产制造",
    chain_level3: "动力锂电池",
    chain_level4: null,
  },
  {
    chain_level1: "新能源锂电",
    chain_level2: "锂电池生产制造",
    chain_level3: "消费锂电池",
    chain_level4: null,
  },
  {
    chain_level1: "新能源锂电",
    chain_level2: "锂电池生产制造",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "新能源锂电",
    chain_level2: null,
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "产业服务",
    chain_level3: "CDMO",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "产业服务",
    chain_level3: "CRO",
    chain_level4: "临床CRO",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "产业服务",
    chain_level3: "CRO",
    chain_level4: "临床前CRO",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "产业服务",
    chain_level3: "CRO",
    chain_level4: "注册申报CRO",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "产业服务",
    chain_level3: "CRO",
    chain_level4: "药物发现CRO",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "产业服务",
    chain_level3: "CRO",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "产业服务",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "关键装备与原辅料",
    chain_level3: "制药设备",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "关键装备与原辅料",
    chain_level3: "药品原辅料",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "关键装备与原辅料",
    chain_level3: "药用包材",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "关键装备与原辅料",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "中医器械",
    chain_level4: "中医器具",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "中医器械",
    chain_level4: "中医治疗设备",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "中医器械",
    chain_level4: "中医诊断设备",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "中医器械",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "体外诊断",
    chain_level4: "免疫诊断",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "体外诊断",
    chain_level4: "分子诊断",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "体外诊断",
    chain_level4: "微生物诊断",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "体外诊断",
    chain_level4: "生化诊断",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "体外诊断",
    chain_level4: "血液诊断",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "体外诊断",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医学影像",
    chain_level4: "光学成像",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医学影像",
    chain_level4: "内窥镜",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医学影像",
    chain_level4: "医用X射线",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医学影像",
    chain_level4: "图像显示、处理、传输及打印设备",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医学影像",
    chain_level4: "放射性核素成像",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医学影像",
    chain_level4: "核磁共振",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医学影像",
    chain_level4: "组合功能融合成像器械",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医学影像",
    chain_level4: "超声",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医学影像",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医用可穿戴设备",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医用软件",
    chain_level4: "体外诊断类软件",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医用软件",
    chain_level4: "其他医用软件",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医用软件",
    chain_level4: "决策支持软件",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医用软件",
    chain_level4: "影像处理软件",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医用软件",
    chain_level4: "数据处理软件",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医用软件",
    chain_level4: "治疗计划软件",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医用软件",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医疗机器人",
    chain_level4: "医疗服务机器人",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医疗机器人",
    chain_level4: "医疗辅助机器人",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医疗机器人",
    chain_level4: "康复机器人",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医疗机器人",
    chain_level4: "手术机器人",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "医疗机器人",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "康复器械",
    chain_level4: "助行器械",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "康复器械",
    chain_level4: "康复机器人",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "康复器械",
    chain_level4: "矫形固定器械",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "康复器械",
    chain_level4: "认知言语视听障碍康复设备",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "康复器械",
    chain_level4: "运动康复训练器械",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "康复器械",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "放疗器械",
    chain_level4: "放射治疗准直线束器械",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "放疗器械",
    chain_level4: "放射治疗模拟定位设备",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "放疗器械",
    chain_level4: "放射治疗设备",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "放疗器械",
    chain_level4: "放射治疗配套器械",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "放疗器械",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "输血/透析",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "高值耗材",
    chain_level4: "人工器官、组织及配套材料",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "高值耗材",
    chain_level4: "口腔科耗材",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "高值耗材",
    chain_level4: "吻合器及附件",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "高值耗材",
    chain_level4: "心脏外科耗材",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "高值耗材",
    chain_level4: "眼科耗材",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "高值耗材",
    chain_level4: "神经外科耗材",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "高值耗材",
    chain_level4: "血液净化耗材",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "高值耗材",
    chain_level4: "血管介入类耗材",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "高值耗材",
    chain_level4: "非血管介入类耗材",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "高值耗材",
    chain_level4: "骨科植入物",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: "高值耗材",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗器械",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗服务",
    chain_level3: "互联网医疗",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗服务",
    chain_level3: "医疗信息化",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗服务",
    chain_level3: "第三方医疗机构",
    chain_level4: "第三方医学影像中心",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗服务",
    chain_level3: "第三方医疗机构",
    chain_level4: "第三方独立医学实验室",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗服务",
    chain_level3: "第三方医疗机构",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "医疗服务",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "药物研发",
    chain_level3: "中药",
    chain_level4: "中成药",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "药物研发",
    chain_level3: "中药",
    chain_level4: "中药材加工",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "药物研发",
    chain_level3: "中药",
    chain_level4: "中药材种植/养殖",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "药物研发",
    chain_level3: "中药",
    chain_level4: "中药饮片",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "药物研发",
    chain_level3: "中药",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "药物研发",
    chain_level3: "化学药",
    chain_level4: "化学制剂",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "药物研发",
    chain_level3: "化学药",
    chain_level4: "原料药",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "药物研发",
    chain_level3: "化学药",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "药物研发",
    chain_level3: "生物药",
    chain_level4: "基因治疗",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "药物研发",
    chain_level3: "生物药",
    chain_level4: "抗体药物",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "药物研发",
    chain_level3: "生物药",
    chain_level4: "疫苗",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "药物研发",
    chain_level3: "生物药",
    chain_level4: "蛋白药物",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "药物研发",
    chain_level3: "生物药",
    chain_level4: "血液制品",
  },
  {
    chain_level1: "生物医药",
    chain_level2: "药物研发",
    chain_level3: "生物药",
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: "药物研发",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "生物医药",
    chain_level2: null,
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "广播电视设备制造",
    chain_level4: "广播电视制作、发射、传输设备",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "广播电视设备制造",
    chain_level4: "广播电视接收设备",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "广播电视设备制造",
    chain_level4: "应用电视设备及其他广播电视设备",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "广播电视设备制造",
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "应用电子仪器制造",
    chain_level4: "其他专用电子仪器制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "应用电子仪器制造",
    chain_level4: "医疗电子仪器及设备制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "应用电子仪器制造",
    chain_level4: "家电用电子仪器制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "应用电子仪器制造",
    chain_level4: "电子测量仪器",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "应用电子仪器制造",
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子信息专用材料制造",
    chain_level4: "信息化学材料制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子信息专用材料制造",
    chain_level4: "半导体材料制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子信息专用材料制造",
    chain_level4: "电子元件材料制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子信息专用材料制造",
    chain_level4: "真空电子器件材料制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子信息专用材料制造",
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子信息机电产品制造",
    chain_level4: "光纤、光缆制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子信息机电产品制造",
    chain_level4: "电子微电机制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子信息机电产品制造",
    chain_level4: "电子电线电缆制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子信息机电产品制造",
    chain_level4: "电池制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子信息机电产品制造",
    chain_level4: "电阻电容电感元件",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子信息机电产品制造",
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子元器件产品",
    chain_level4: "光电子器件及其他电子器件制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子元器件产品",
    chain_level4: "半导体分立器件",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子元器件产品",
    chain_level4: "敏感元件及传感器",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子元器件产品",
    chain_level4: "电子元件及组件制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子元器件产品",
    chain_level4: "电子印制电路板",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子元器件产品",
    chain_level4: "集成电路制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子元器件产品",
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子工业专用设备产品",
    chain_level4: "半导体器件和集成电路专用设备",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子工业专用设备产品",
    chain_level4: "电子元件专用设备",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子工业专用设备产品",
    chain_level4: "电子整机装联设备",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子工业专用设备产品",
    chain_level4: "电子通用设备",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子工业专用设备产品",
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子计算机制造",
    chain_level4: "电子计算机外部设备制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子计算机制造",
    chain_level4: "电子计算机整机制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子计算机制造",
    chain_level4: "电子计算机配套产品及耗材",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子计算机制造",
    chain_level4: "计算机网络设备制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "电子计算机制造",
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "通信设备制造",
    chain_level4: "5G网络传输设备制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "通信设备制造",
    chain_level4: "移动通信设备制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "通信设备制造",
    chain_level4: "通信交换设备制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "通信设备制造",
    chain_level4: "通信终端设备制造",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: "通信设备制造",
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "元器件、设备及材料制造业",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "电子信息应用领域",
    chain_level3: "人工智能",
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "电子信息应用领域",
    chain_level3: "区块链",
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "电子信息应用领域",
    chain_level3: "大数据",
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "电子信息应用领域",
    chain_level3: "工业互联网",
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "电子信息应用领域",
    chain_level3: "新型显示",
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "电子信息应用领域",
    chain_level3: "物联网",
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "电子信息应用领域",
    chain_level3: "虚拟现实",
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "电子信息应用领域",
    chain_level3: "集成电路",
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "电子信息应用领域",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "软件开发、制造与服务业",
    chain_level3: "信息技术服务业",
    chain_level4: "信息技术咨询服务",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "软件开发、制造与服务业",
    chain_level3: "信息技术服务业",
    chain_level4: "信息系统集成服务",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "软件开发、制造与服务业",
    chain_level3: "信息技术服务业",
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "软件开发、制造与服务业",
    chain_level3: "软件开发",
    chain_level4: "信息安全软件",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "软件开发、制造与服务业",
    chain_level3: "软件开发",
    chain_level4: "应用软件",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "软件开发、制造与服务业",
    chain_level3: "软件开发",
    chain_level4: "底层软件",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "软件开发、制造与服务业",
    chain_level3: "软件开发",
    chain_level4: "支撑软件",
  },
  {
    chain_level1: "电子信息",
    chain_level2: "软件开发、制造与服务业",
    chain_level3: "软件开发",
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: "软件开发、制造与服务业",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "电子信息",
    chain_level2: null,
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "纺织鞋服",
    chain_level2: "上游原料及设备",
    chain_level3: "化学纤维",
    chain_level4: "合成纤维",
  },
  {
    chain_level1: "纺织鞋服",
    chain_level2: "上游原料及设备",
    chain_level3: "化学纤维",
    chain_level4: null,
  },
  {
    chain_level1: "纺织鞋服",
    chain_level2: "上游原料及设备",
    chain_level3: "天然原料",
    chain_level4: "动物皮毛",
  },
  {
    chain_level1: "纺织鞋服",
    chain_level2: "上游原料及设备",
    chain_level3: "天然原料",
    chain_level4: "植物纤维",
  },
  {
    chain_level1: "纺织鞋服",
    chain_level2: "上游原料及设备",
    chain_level3: "天然原料",
    chain_level4: null,
  },
  {
    chain_level1: "纺织鞋服",
    chain_level2: "上游原料及设备",
    chain_level3: "纺织机械",
    chain_level4: null,
  },
  {
    chain_level1: "纺织鞋服",
    chain_level2: "上游原料及设备",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "纺织鞋服",
    chain_level2: "下游应用领域",
    chain_level3: "家用纺织品",
    chain_level4: null,
  },
  {
    chain_level1: "纺织鞋服",
    chain_level2: "下游应用领域",
    chain_level3: "工业用纺织品",
    chain_level4: null,
  },
  {
    chain_level1: "纺织鞋服",
    chain_level2: "下游应用领域",
    chain_level3: "服装",
    chain_level4: null,
  },
  {
    chain_level1: "纺织鞋服",
    chain_level2: "下游应用领域",
    chain_level3: "皮具箱包",
    chain_level4: null,
  },
  {
    chain_level1: "纺织鞋服",
    chain_level2: "下游应用领域",
    chain_level3: "鞋业",
    chain_level4: null,
  },
  {
    chain_level1: "纺织鞋服",
    chain_level2: "下游应用领域",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "纺织鞋服",
    chain_level2: "中游纺织制造",
    chain_level3: "印花",
    chain_level4: null,
  },
  {
    chain_level1: "纺织鞋服",
    chain_level2: "中游纺织制造",
    chain_level3: "染色",
    chain_level4: null,
  },
  {
    chain_level1: "纺织鞋服",
    chain_level2: "中游纺织制造",
    chain_level3: "纤维加工",
    chain_level4: null,
  },
  {
    chain_level1: "纺织鞋服",
    chain_level2: "中游纺织制造",
    chain_level3: "织造",
    chain_level4: null,
  },
  {
    chain_level1: "纺织鞋服",
    chain_level2: "中游纺织制造",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "纺织鞋服",
    chain_level2: null,
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "上游原料、辅料及加工设备",
    chain_level3: "农业生产资料",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "上游原料、辅料及加工设备",
    chain_level3: "初级农产品",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "上游原料、辅料及加工设备",
    chain_level3: "食品包装材料",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "上游原料、辅料及加工设备",
    chain_level3: "食品添加剂",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "上游原料、辅料及加工设备",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "中游加工制造",
    chain_level3: "农副食品加工业",
    chain_level4: "其他农副食品加工",
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "中游加工制造",
    chain_level3: "农副食品加工业",
    chain_level4: "水产品加工",
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "中游加工制造",
    chain_level3: "农副食品加工业",
    chain_level4: "油料作物加工",
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "中游加工制造",
    chain_level3: "农副食品加工业",
    chain_level4: "蔬菜、菌类、水果和坚果加工",
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "中游加工制造",
    chain_level3: "农副食品加工业",
    chain_level4: "谷物磨制品",
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "中游加工制造",
    chain_level3: "农副食品加工业",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "中游加工制造",
    chain_level3: "酒、饮料和精制茶制造业",
    chain_level4: "精制茶",
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "中游加工制造",
    chain_level3: "酒、饮料和精制茶制造业",
    chain_level4: "酒类",
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "中游加工制造",
    chain_level3: "酒、饮料和精制茶制造业",
    chain_level4: "饮料",
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "中游加工制造",
    chain_level3: "酒、饮料和精制茶制造业",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "中游加工制造",
    chain_level3: "食品制造业",
    chain_level4: "乳制品",
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "中游加工制造",
    chain_level3: "食品制造业",
    chain_level4: "其他绿色食品",
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "中游加工制造",
    chain_level3: "食品制造业",
    chain_level4: "方便食品",
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "中游加工制造",
    chain_level3: "食品制造业",
    chain_level4: "烘焙食品",
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "中游加工制造",
    chain_level3: "食品制造业",
    chain_level4: "糖果和蜜饯",
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "中游加工制造",
    chain_level3: "食品制造业",
    chain_level4: "膨化食品",
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "中游加工制造",
    chain_level3: "食品制造业",
    chain_level4: "调味品和发酵制品",
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "中游加工制造",
    chain_level3: "食品制造业",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "中游加工制造",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "农副食品加工业",
    chain_level3: "其他农副食品加工",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "农副食品加工业",
    chain_level3: "水产品加工",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "农副食品加工业",
    chain_level3: "油料作物加工",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "农副食品加工业",
    chain_level3: "蔬菜、菌类、水果和坚果加工",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "农副食品加工业",
    chain_level3: "谷物磨制品",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "农副食品加工业",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "酒、饮料和精制茶制造业",
    chain_level3: "精制茶",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "酒、饮料和精制茶制造业",
    chain_level3: "酒类",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "酒、饮料和精制茶制造业",
    chain_level3: "饮料",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "酒、饮料和精制茶制造业",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "食品制造业",
    chain_level3: "乳制品",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "食品制造业",
    chain_level3: "其他绿色食品",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "食品制造业",
    chain_level3: "方便食品",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "食品制造业",
    chain_level3: "烘焙食品",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "食品制造业",
    chain_level3: "糖果和蜜饯",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "食品制造业",
    chain_level3: "膨化食品",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "食品制造业",
    chain_level3: "调味品和发酵制品",
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: "食品制造业",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "绿色食品",
    chain_level2: null,
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "节能环保",
    chain_level2: "先进环保产业",
    chain_level3: "环保相关设备",
    chain_level4: "环境保护监测仪器及电子设备",
  },
  {
    chain_level1: "节能环保",
    chain_level2: "先进环保产业",
    chain_level3: "环保相关设备",
    chain_level4: null,
  },
  {
    chain_level1: "节能环保",
    chain_level2: "先进环保产业",
    chain_level3: "环境治理与监测服务",
    chain_level4: "环境保护及污染治理服务",
  },
  {
    chain_level1: "节能环保",
    chain_level2: "先进环保产业",
    chain_level3: "环境治理与监测服务",
    chain_level4: null,
  },
  {
    chain_level1: "节能环保",
    chain_level2: "先进环保产业",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "节能环保",
    chain_level2: "资源循环利用产业",
    chain_level3: "工业废弃物资源化利用",
    chain_level4: null,
  },
  {
    chain_level1: "节能环保",
    chain_level2: "资源循环利用产业",
    chain_level3: "矿产资源综合利用",
    chain_level4: null,
  },
  {
    chain_level1: "节能环保",
    chain_level2: "资源循环利用产业",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "节能环保",
    chain_level2: "高效节能产业",
    chain_level3: "高效节能装置与器械",
    chain_level4: "高效节能工业控制装置",
  },
  {
    chain_level1: "节能环保",
    chain_level2: "高效节能产业",
    chain_level3: "高效节能装置与器械",
    chain_level4: "高效节能电气机械器材制造",
  },
  {
    chain_level1: "节能环保",
    chain_level2: "高效节能产业",
    chain_level3: "高效节能装置与器械",
    chain_level4: null,
  },
  {
    chain_level1: "节能环保",
    chain_level2: "高效节能产业",
    chain_level3: null,
    chain_level4: null,
  },
  {
    chain_level1: "节能环保",
    chain_level2: null,
    chain_level3: null,
    chain_level4: null,
  },
];
